# coding: utf-8

"""
    User Information Service

    FABRIC User Information Service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: ibaldin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SshKeyBastion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'public_openssh': 'str',
        'login': 'str',
        'gecos': 'str',
        'status': 'SshKeyStatus'
    }

    attribute_map = {
        'public_openssh': 'public_openssh',
        'login': 'login',
        'gecos': 'gecos',
        'status': 'status'
    }

    def __init__(self, public_openssh=None, login=None, gecos=None, status=None):  # noqa: E501
        """SshKeyBastion - a model defined in Swagger"""  # noqa: E501
        self._public_openssh = None
        self._login = None
        self._gecos = None
        self._status = None
        self.discriminator = None
        if public_openssh is not None:
            self.public_openssh = public_openssh
        if login is not None:
            self.login = login
        if gecos is not None:
            self.gecos = gecos
        if status is not None:
            self.status = status

    @property
    def public_openssh(self):
        """Gets the public_openssh of this SshKeyBastion.  # noqa: E501


        :return: The public_openssh of this SshKeyBastion.  # noqa: E501
        :rtype: str
        """
        return self._public_openssh

    @public_openssh.setter
    def public_openssh(self, public_openssh):
        """Sets the public_openssh of this SshKeyBastion.


        :param public_openssh: The public_openssh of this SshKeyBastion.  # noqa: E501
        :type: str
        """

        self._public_openssh = public_openssh

    @property
    def login(self):
        """Gets the login of this SshKeyBastion.  # noqa: E501


        :return: The login of this SshKeyBastion.  # noqa: E501
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """Sets the login of this SshKeyBastion.


        :param login: The login of this SshKeyBastion.  # noqa: E501
        :type: str
        """

        self._login = login

    @property
    def gecos(self):
        """Gets the gecos of this SshKeyBastion.  # noqa: E501


        :return: The gecos of this SshKeyBastion.  # noqa: E501
        :rtype: str
        """
        return self._gecos

    @gecos.setter
    def gecos(self, gecos):
        """Sets the gecos of this SshKeyBastion.


        :param gecos: The gecos of this SshKeyBastion.  # noqa: E501
        :type: str
        """

        self._gecos = gecos

    @property
    def status(self):
        """Gets the status of this SshKeyBastion.  # noqa: E501


        :return: The status of this SshKeyBastion.  # noqa: E501
        :rtype: SshKeyStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SshKeyBastion.


        :param status: The status of this SshKeyBastion.  # noqa: E501
        :type: SshKeyStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SshKeyBastion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SshKeyBastion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
