# coding: utf-8

"""
    User Information Service

    FABRIC User Information Service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: ibaldin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.preferences_api import PreferencesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPreferencesApi(unittest.TestCase):
    """PreferencesApi unit test stubs"""

    def setUp(self):
        self.api = PreferencesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_preferences_preftype_uuid_get(self):
        """Test case for preferences_preftype_uuid_get

        get user preferences of specific type (settings, permissions or interests; open only to self)  # noqa: E501
        """
        pass

    def test_preferences_preftype_uuid_put(self):
        """Test case for preferences_preftype_uuid_put

        update user preferences by type (open only to self)  # noqa: E501
        """
        pass

    def test_preferences_uuid_get(self):
        """Test case for preferences_uuid_get

        get all user preferences as an object (open only to self)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
