# coding: utf-8

"""
    User Information Service

    FABRIC User Information Service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: ibaldin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ssh_key_bastion import SshKeyBastion  # noqa: E501
from swagger_client.rest import ApiException


class TestSshKeyBastion(unittest.TestCase):
    """SshKeyBastion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSshKeyBastion(self):
        """Test SshKeyBastion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ssh_key_bastion.SshKeyBastion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
