# coding: utf-8

"""
    User Information Service

    FABRIC User Information Service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: ibaldin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sshkeys_api import SshkeysApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSshkeysApi(unittest.TestCase):
    """SshkeysApi unit test stubs"""

    def setUp(self):
        self.api = SshkeysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bastionkeys_get(self):
        """Test case for bastionkeys_get

        Get a list of bastion keys that were created, deactivated or expired since specified date in UTC (open to Bastion hosts)  # noqa: E501
        """
        pass

    def test_sshkey_keyid_delete(self):
        """Test case for sshkey_keyid_delete

        Delete a specified key based on key UUID (open only to self)  # noqa: E501
        """
        pass

    def test_sshkey_keyid_get(self):
        """Test case for sshkey_keyid_get

        get metadata, including expiration date for this key based on key UUID (open only to self)  # noqa: E501
        """
        pass

    def test_sshkey_keytype_post(self):
        """Test case for sshkey_keytype_post

        Add a user-provided ssh public key of specified type. (open only to self)  # noqa: E501
        """
        pass

    def test_sshkey_keytype_put(self):
        """Test case for sshkey_keytype_put

        Generate a new SSH key of specified type. Return both public and private portions. (open only to self)  # noqa: E501
        """
        pass

    def test_sshkey_uuid_keyid_get(self):
        """Test case for sshkey_uuid_keyid_get

        Get a specific key of a given user (open to any valid user)  # noqa: E501
        """
        pass

    def test_sshkeys_get(self):
        """Test case for sshkeys_get

        Get a list of all active/non-expired keys of this user (open to self)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
