# coding: utf-8

"""
    User Information Service

    FABRIC User Information Service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: ibaldin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.publications_api import PublicationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicationsApi(unittest.TestCase):
    """PublicationsApi unit test stubs"""

    def setUp(self):
        self.api = PublicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authorids_idtype_uuid_get(self):
        """Test case for authorids_idtype_uuid_get

        get users specific author ID (open only to self)  # noqa: E501
        """
        pass

    def test_authorids_idtype_uuid_put(self):
        """Test case for authorids_idtype_uuid_put

        update user's specific author ID (open only to self)  # noqa: E501
        """
        pass

    def test_authorids_uuid_get(self):
        """Test case for authorids_uuid_get

        get user's author IDs (Scopus, Orcid etc.; open only to self)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
