# coding: utf-8

"""
    User Information Service

    FABRIC User Information Service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: ibaldin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.people_api import PeopleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPeopleApi(unittest.TestCase):
    """PeopleApi unit test stubs"""

    def setUp(self):
        self.api = PeopleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_people_get(self):
        """Test case for people_get

        list of people (open to any valid user)  # noqa: E501
        """
        pass

    def test_people_uuid_get(self):
        """Test case for people_uuid_get

        person details by UUID (open only to self)  # noqa: E501
        """
        pass

    def test_people_whoami_get(self):
        """Test case for people_whoami_get

        Details about self from OIDC Claim sub provided in ID token; Creates new entry; (open only to self)  # noqa: E501
        """
        pass

    def test_uuid_oidc_claim_sub_get(self):
        """Test case for uuid_oidc_claim_sub_get

        get person UUID based on their OIDC claim sub (open to any valid user)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
