# coding: utf-8

"""
    User Information Service

    FABRIC User Information Service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: ibaldin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.preference_type import PreferenceType  # noqa: E501
from swagger_client.rest import ApiException


class TestPreferenceType(unittest.TestCase):
    """PreferenceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreferenceType(self):
        """Test PreferenceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.preference_type.PreferenceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
